name: Update Release Draft

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Release Draft
        uses: release-drafter/release-drafter@v7
        with:
          config-name: .github/release-drafter.yml
